const views=[
  {id:'course',tab:'课程',title:'推荐学习路径',left:'课程项目链'},
  {id:'project',tab:'项目',title:'项目四：5G端到端网络优化',left:'项目链'},
  {id:'task',tab:'项目',title:'P4-T2 5G网络优化结果验证',left:'P4-T2 能力节点'},
  {id:'self',tab:'课程',title:'P4T2-N04 读移动性指标',left:'教材目录'},
  {id:'graph',tab:'图谱',title:'课程能力图谱',left:'图谱筛选'},
  {id:'teacher',tab:'教师',title:'教师授课控制台',left:'课件页'},
  {id:'projector',tab:'教师',title:'投屏端',left:'投屏页'},
  {id:'follow',tab:'课程',title:'学生课堂跟随',left:'课堂页'}
];
const state={view:'course',step:2,free:false,pushed:false,submitted:false,answer:{q1:'',q2:'',why:'',conclusion:''},playing:false};
const projects=[['P1','5G网络信息采集','信息采集 · 结构占位'],['P2','5G网络测试','网络测试 · 已接入闭环'],['P3','5G网络信息管理','信息管理 · 结构占位'],['P4','5G端到端网络优化','优化实施与结果验证 · 已接入闭环'],['P5','5G全网性能提升','性能提升 · 结构占位'],['P6','5G信令分析','信令分析 · 结构占位']];
const nodes=[['01','识别验证场景','确定需要验证的问题和场景'],['02','区分改善与达标','区分指标改善与是否达标'],['03','读覆盖指标','读取RSRP/SINR等覆盖指标'],['04','读移动性指标','读取切换成功率、掉线等指标'],['05','读体验容量指标','读取速率、时延、容量等指标'],['06','选择判断依据','选择关键依据支撑结论'],['07','形成验收结论','形成可交付的验收结论'],['08','修正职业表达','优化报告表达，符合规范']];
const metrics=[['RSRP覆盖率','97.5%','目标 >=95%','good'],['SINR覆盖率','92.0%','目标 >=90%','good'],['切换成功率','94.5%','目标 >=98%','bad'],['10次往返重建','4次','目标 <=1次','bad'],['短掉线日志','1段','待复核','wait']];
const $=s=>document.querySelector(s);
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1400)}
function activeTab(){return views.find(v=>v.id===state.view).tab}
function renderTabs(){const tabs=['课程','项目','图谱','教师'];$('#topTabs').innerHTML=tabs.map(t=>`<button class="tab ${t===activeTab()?'active':''}" onclick="go('${t==='课程'?'course':t==='项目'?'project':t==='图谱'?'graph':'teacher'}')">${t}</button>`).join('')}
function hero(kind,subtitle=''){const v=views.find(x=>x.id===state.view);return `<section class="card hero"><div class="hero-head"><span class="pill">${kind}</span><h2>${v.title}</h2><span class="mini">${state.free?'自学自由':'课堂跟随'}</span></div><p>${subtitle}</p></section>`}
function renderLeft(){let list='',hint='';if(['course','project'].includes(state.view)){list=projects.map((x,i)=>`<button class="lesson ${i===3?'active':''}" onclick="go('${i===3?'project':'graph'}')"><b>${x[0]}</b><div><strong>${x[1]}</strong><span>${x[2]}</span></div></button>`).join('');hint='当前样板重点验证：课程首页 → 项目四 → P4-T2完整任务 → N04节点 → 教师与学生课堂联动。'}else if(state.view==='graph'){list=['课程主链','项目路径','任务节点','能力节点','资源卡片','评价产出'].map((x,i)=>`<button class="lesson ${i===0?'active':''}"><b>${i+1}</b><div><strong>${x}</strong><span>图谱关系层</span></div></button>`).join('');hint='图谱负责解释内容位置，并把资源、活动、评价和教材正文双向定位。'}else{list=nodes.slice(0,state.view==='teacher'?5:nodes.length).map((n,i)=>`<button class="lesson ${i===state.step?'active':''}" onclick="state.step=${i};render()"><b>${i+1}</b><div><strong>${n[1]}</strong><span>${n[2]}</span></div></button>`).join('');hint=state.view==='follow'?'学生跟随页用于完成课堂小任务，教师推送后可作答提交。':'教师端负责讲解、推送、投屏和讲评，不显示为学生教材正文。'}$('#leftTitle').textContent=views.find(v=>v.id===state.view).left;$('#leftList').innerHTML=list;$('#leftHint').innerHTML='<b>提示</b><br>'+hint;$('#pageIndex').textContent=state.view==='teacher'?'3 / 5':state.view==='follow'?'第 3 页 / 5 页':'P4-T2'}
function sideStudent(){return `<h3>课堂小任务（本页）</h3><div class="card task-card"><div class="task-title"><span class="num">1</span><span>判断投诉发生在静止点还是移动路径？</span></div><select id="q1"><option>请选择</option><option ${state.answer.q1==='静止点'?'selected':''}>静止点</option><option ${state.answer.q1==='移动路径'?'selected':''}>移动路径</option></select></div><div class="card task-card"><div class="task-title"><span class="num">2</span><span>标注一个未闭环依据（证据）</span></div><select id="q2"><option>请选择证据类型</option><option ${state.answer.q2==='切换成功率未达标'?'selected':''}>切换成功率未达标</option><option ${state.answer.q2==='重建次数偏多'?'selected':''}>重建次数偏多</option><option ${state.answer.q2==='短掉线日志存在'?'selected':''}>短掉线日志存在</option></select><textarea id="why" maxlength="60" placeholder="简要说明依据（可选）">${state.answer.why}</textarea><div class="count"><span id="whyCount">${state.answer.why.length}</span>/60</div></div><div class="card task-card"><div class="task-title"><span class="num">3</span><span>写一句边界结论</span></div><textarea id="conclusion" maxlength="60" placeholder="请输入你的结论">${state.answer.conclusion}</textarea><div class="count"><span id="conclusionCount">${state.answer.conclusion.length}</span>/60</div></div><div class="card task-card"><div class="section-title"><span>参考结论</span><button class="mini" onclick="fillDemo()">填入示例</button></div><div class="note-blue">覆盖改善，但移动性未闭环，需要继续复核邻区关系或切换参数。</div></div>`}
function sideDefault(){return `<h3>学习上下文</h3><div class="card task-card"><div class="task-title"><span class="num">N04</span><span>读移动性指标</span></div><p class="note-blue">通过移动性指标判断终端在电梯口到食堂路径中的切换行为，为移动性验证提供依据。</p></div><div class="card task-card"><div class="section-title"><span>关联资源</span></div><div class="path"><button class="outline" onclick="go('self')">N04 学生自学页</button><button class="outline" onclick="go('teacher')">N04 教师授课页</button><button class="outline" onclick="go('projector')">N04 投屏页</button></div></div><div class="card task-card"><div class="section-title"><span>评价产出</span></div><div class="note-blue">移动性验证流程 + 闭环边界表达。</div></div>`}
function metricTable(){return `<div class="table-wrap"><table class="table"><thead><tr><th>维度</th><th>关键指标</th><th>当前值</th><th>目标值</th><th>状态</th><th>证据来源</th></tr></thead><tbody><tr><td>覆盖</td><td>SS-RSRP覆盖率</td><td>97.5%</td><td>>=95%</td><td class="status-good">已达标</td><td>路测报告</td></tr><tr><td>覆盖</td><td>SS-SINR覆盖率</td><td>92.0%</td><td>>=90%</td><td class="status-good">已达标</td><td>路测报告</td></tr><tr><td>移动性</td><td>切换成功率</td><td>94.5%</td><td>>=98%</td><td class="status-bad">未达标</td><td>路测报告</td></tr><tr><td>移动性</td><td>10次往返重建次数</td><td>4次</td><td><=1次</td><td class="status-bad">未达标</td><td>路测报告</td></tr><tr><td>日志</td><td>短掉线日志</td><td>1段</td><td>无连续掉线</td><td class="status-wait">待复核</td><td>日志分析</td></tr></tbody></table></div>`}
function flow(){return `<div class="flow-stage"><svg viewBox="0 0 760 300"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#1768ff"/><stop offset="1" stop-color="#7b35e8"/></linearGradient></defs><path d="M55 150 C155 108 235 145 310 125 S455 150 530 124 S640 128 725 168" fill="none" stroke="url(#g)" stroke-width="10" stroke-linecap="round"/><path d="M110 178 C195 212 260 182 345 194 S492 184 610 212" fill="none" stroke="#b8c3d5" stroke-width="3" stroke-dasharray="8 9"/>${[['1',95,150],['2',310,126],['3',530,126],['4',700,160]].map((n,i)=>`<g><circle cx="${n[1]}" cy="${n[2]}" r="28" fill="#fff" stroke="${i>1?'#7b35e8':'#1768ff'}" stroke-width="5"/><text x="${n[1]}" y="${n[2]+8}" text-anchor="middle" font-size="26" font-weight="900" fill="${i>1?'#7b35e8':'#1768ff'}">${n[0]}</text></g>`).join('')}</svg><div class="flow-label l1">电梯口</div><div class="flow-label l2">A-B边界</div><div class="flow-label l3">食堂入口</div><div class="flow-label l4">就餐区</div></div><div class="warn">覆盖已改善，但移动性未闭环</div>`}
function evidence(){return `<div class="evidence"><div class="ev bad"><i>↔</i><div><strong>切换成功率</strong><span>目标 >=98%，当前未达标</span></div><b>94.5%</b></div><div class="ev bad"><i>↻</i><div><strong>10次往返重建</strong><span>目标 <=1次，当前未达标</span></div><b>4次</b></div><div class="ev"><i>▣</i><div><strong>短掉线日志</strong><span>需要结合日志进一步复核</span></div><b>1段</b></div><div class="note-blue">提示：三项证据同时指向移动性未闭环，不能只凭覆盖改善判断任务完成。</div></div>`}
function course(){return `<section class="course-hero card"><div><span class="eyebrow">正在学习：项目四 5G端到端网络优化</span><h2>P4-T2 5G网络优化结果验证 <span>当前推荐</span></h2><p>在 P4-T1 优化实施的基础上，基于验证方法和指标体系，对优化效果进行全面评估与验证，形成可靠结论，为报告输出提供依据。</p><div class="hero-meta"><span>建议学时 3.5</span><span>难度 ★★★★☆</span><span>学习目标 3 项</span></div><button class="primary" onclick="go('task')">进入P4-T2任务学习 →</button></div><div class="radar-card"><div class="radar"></div></div></section><section class="course-layout"><div class="card pad"><div class="section-title"><span>任务链摘要</span></div><div class="task-chain"><div class="chain-card done"><b>P4-T1</b><strong>优化实施</strong><p>制定并实施优化方案。</p><span>已完成</span></div><div class="chain-arrow">→</div><div class="chain-card active"><b>P4-T2</b><strong>结果验证</strong><p>验证优化效果，确认是否达成目标。</p><span>当前任务</span></div><div class="chain-arrow">→</div><div class="chain-card"><b>P4-T3</b><strong>报告输出</strong><p>整理验证结论并提出建议。</p><span>待学习</span></div></div><div class="evidence-strip"><b>P2-T3 测试数据</b><span>DT/CQT测试、问题处理与测试数据分析结果</span><button class="outline" onclick="go('graph')">查看证据详情 →</button></div></div><div class="card pad"><div class="section-title"><span>学习上下文</span></div><div class="context-card"><b>当前推荐</b><strong>P4-T2 5G网络优化结果验证</strong><p>基于验证方法与指标体系，评估优化效果，形成可靠结论。</p><button class="outline" onclick="go('task')">查看任务详情 →</button></div><div class="context-card"><b>能力图谱</b><p>指标体系应用、数据分析能力、验证评估能力。</p><button class="outline" onclick="go('graph')">查看能力图谱详情 →</button></div></div></section>`}
function project(){return hero('项目路径','表达 P4-T1、P4-T2、P4-T3 的前后关系，并说明 P4-T2 内部 N01-N08 能力节点。')+`<section class="grid"><div class="card pad"><div class="section-title"><span>项目四任务链</span></div><div class="project-chain"><div><b>P4-T1</b><strong>优化实施</strong><span>已完成</span></div><div class="active"><b>P4-T2</b><strong>结果验证</strong><span>进行中</span><button onclick="go('task')">进入</button></div><div><b>P4-T3</b><strong>报告输出</strong><span>待开始</span></div></div><div class="section-title"><span>任务能力节点（P4-T2）</span></div><div class="node-grid">${nodes.map((n,i)=>`<button class="node-card ${i===3?'active':''}" onclick="go('${i===3?'self':'graph'}')"><b>${n[0]}</b><strong>${n[1]}</strong><span>${n[2]}</span></button>`).join('')}</div></div><div class="card pad"><div class="section-title"><span>完成产出</span></div><ul class="clean"><li>优化结果验证记录表</li><li>指标对比分析图表</li><li>问题改善清单</li><li>验收结论与建议</li></ul><button class="primary full" onclick="go('task')">进入学习</button></div></section>`}
function task(){return hero('完整任务','通过多维 KPI 验证，判断优化是否真正达标并闭环，形成规范验收结论。')+`<section class="task-page"><div class="card pad"><div class="section-title"><span>案例问题</span><button class="outline" onclick="go('self')">进入N04自学</button></div><p class="note-blue">优化后台显示覆盖指标改善，现场测试 RSRP 与 SINR 明显改善，但用户在移动过程中仍出现通话或视频中断。需要通过数据验证：优化后是否真正达标并闭环？</p></div><div class="card pad"><div class="section-title"><span>指标解释与 KPI 证据表</span></div>${metricTable()}</div><div class="card pad span"><div class="section-title"><span>判断活动（七步闭环）</span></div><div class="step-cards">${nodes.slice(0,7).map((n,i)=>`<div class="step-card ${i===3?'active':''}"><b>${i+1}</b><strong>${n[1]}</strong><span>${n[2]}</span></div>`).join('')}</div></div><div class="card pad"><div class="section-title"><span>结论表达框</span></div><p class="note-blue"><b>验收结论：</b>覆盖改善，但移动性未闭环，需要继续复核邻区关系或切换参数。</p><p>关键依据：切换成功率 94.5% 未达标，10 次往返重建次数为 4 次，短掉线日志 1 段待复核。</p></div><div class="card pad"><div class="section-title"><span>订正反馈</span></div><p>表达规范性 ★★★★☆</p><p>逻辑完整性 ★★★★☆</p><p>依据充分性 ★★★★☆</p></div></section>`}
function self(){return hero('学生自学页','教材正文以“为什么还会断”为主问题，支持学生脱离教师讲解也能完成学习。')+`<section class="self-page"><aside class="self-menu card"><button class="active">案例导入</button><button>术语解释</button><button>数据阅读</button><button>判断步骤</button><button>完整例子</button><button>反例误区</button><button>动手练习</button></aside><div class="card pad"><h2>P4T2-N04 读移动性指标：移动路径上为什么还会断</h2><h3>案例导入</h3><p>某院校地下食堂已完成优化，静止测试显示覆盖良好；但从电梯口走向食堂的路上，视频会议仍会中断 1-2 秒。</p><h3>术语解释</h3><ul><li>覆盖指标：回答“某个位置有没有信号、信号质量如何”。</li><li>移动性指标：回答“移动过程中能否顺利切换、持续提供服务”。</li><li>移动性未闭环：覆盖合格，但切换效率低、频繁重建或仍有掉线。</li></ul><h3>数据阅读</h3>${metricTable()}<h3>路径与现象图示</h3>${flow()}</div><aside class="study-tasks card pad"><div class="section-title"><span>学习任务</span></div>${['圈出移动性关键词','标注覆盖已改善的依据','标注移动性未闭环依据','写一句结论'].map((x,i)=>`<div class="mini-task"><b>${i+1}</b><span>${x}</span></div>`).join('')}<button class="primary full" onclick="go('follow')">进入课堂跟随</button></aside></section>`}
function graph(){return hero('课程能力图谱','用图谱解释内容为什么在这里，并把资源、活动、评价与能力节点双向定位。')+`<section class="graph-layout"><aside class="graph-filter card pad"><h3>图谱筛选</h3>${['课程主链','项目路径','任务节点','能力节点','资源卡片','评价产出'].map((x,i)=>`<button class="${i===0?'active':''}">${x}</button>`).join('')}</aside><div class="card pad"><div class="section-title"><span>课程能力图谱</span><button class="outline" onclick="go('self')">进入N04自学页</button></div><div class="graph"><svg><path d="M80 100 H210 H340 H470 H600 H730 H860" stroke="#1768ff" stroke-width="3" fill="none"/><path d="M470 126 V230 H330 M470 230 H620 M470 230 V355" stroke="#6d4aff" stroke-width="3" fill="none"/></svg>${[['CG-01<br>信息采集',55,75,92,92],['CG-02<br>网络测试',185,75,92,92],['CG-03<br>信息管理',315,75,92,92],['CG-04<br>优化实施',445,75,92,92],['CG-05<br>结果验证',575,75,96,96,'focus'],['CG-06<br>性能提升',708,75,92,92],['CG-07<br>信令分析',840,75,92,92],['P4-T1<br>结果复核路径',330,230,124,70],['P4-T2<br>移动性验证路径',500,230,124,70,'focus'],['P4-T3<br>边界闭环路径',670,230,124,70],['N04<br>读移动性指标',500,355,88,88,'focus']].map(n=>`<button class="gnode ${n[5]||''}" style="left:${n[1]}px;top:${n[2]}px;width:${n[3]}px;height:${n[4]}px" onclick="go('${String(n[0]).includes('N04')?'self':String(n[0]).includes('P4-T2')?'task':'graph'}')">${n[0]}</button>`).join('')}</div></div><aside class="card pad graph-detail"><h3>节点详情</h3><b>N04 读移动性指标</b><p>通过移动性指标判断终端在电梯口的切换行为，为移动性验证提供依据。</p><button onclick="go('self')">N04 学生自学页</button><button onclick="go('teacher')">N04 教师授课页</button><button onclick="go('projector')">N04 投屏页</button><button onclick="go('self')">移动性指标表</button><button onclick="go('self')">路线示意图</button></aside></section>`}
function teacher(){return hero('教师端','教师授课控制台用于讲解、提问、板书提示、推送练习、同步学生端和打开投屏。')+`<section class="teacher-grid"><aside class="teacher-pages card pad">${['案例导入','覆盖达标不能直接验收','移动性数据提示','流程排序练习','结论修正讲评'].map((x,i)=>`<button class="${i===2?'active':''}"><b>${i+1}</b>${x}</button>`).join('')}</aside><div class="card teacher-main"><div class="section-title"><span>P4T2-N04 移动性验证黄金切片</span><button class="outline" onclick="go('projector')">全屏预览</button></div><h2>覆盖达标后，为什么移动中仍会中断？</h2>${flow()}<div class="section-title"><span>学生学习证据概览</span></div><div class="metric-grid"><div class="metric"><span>本页已提交</span><strong>36 / 42人</strong><span>提交率 85.7%</span></div><div class="metric bad"><span>常见错误</span><strong>18人</strong><span>忽略切换事件集中区</span></div><div class="metric bad"><span>讲评优先级</span><strong>高</strong><span>切换成功率未达标原因</span></div><div class="metric"><span>AI建议</span><strong>采纳</strong><span>基于历史班级数据</span></div></div></div><div class="card script-box"><div class="tabline"><button class="active">讲解脚本</button><button>课堂提问</button><button>板书提示</button><button>典型答案</button></div><div class="script-body"><p>本页讲解重点：移动中断原因分析与证据定位。</p><ol><li>先承认覆盖改善。</li><li>再追问移动路径。</li><li>最后定位切换与保持证据。</li></ol></div></div></section><section class="card pad"><div class="section-title"><span>课堂互动工具</span></div><div class="quick-grid"><button onclick="toast('已发起随堂投票')">随堂投票</button><button onclick="toast('已开启弹幕讨论')">弹幕讨论</button><button onclick="toast('已创建小组任务')">小组任务</button><button onclick="toast('已启动计时器')">计时器</button></div></section>`}
function projector(){return `<section class="slide"><div class="hero-head"><span class="pill">P4T2-N04</span><h2>3 / 5 · 投屏端</h2><button class="tool" onclick="go('teacher')">返回授课台</button></div><h2>覆盖达标后，为什么移动中仍会中断？</h2><p>课堂大屏只展示核心内容：路线、关键证据和边界结论，不展示教师脚本与学生个人作答。</p>${flow()}<div class="kpi-dark">${metrics.slice(0,4).map(m=>`<div><span>${m[0]}</span><strong style="color:${m[3]==='bad'?'#fca5a5':'#6ee7b7'}">${m[1]}</strong><p>${m[2]}</p></div>`).join('')}</div></section>`}
function follow(){return hero('课堂跟随','学生端跟随教师当前讲解页，完成选择、证据标注和边界结论提交。')+`<section class="follow-page"><div class="card pad follow-main"><div class="section-title"><span>本页核心问题</span><button class="outline" onclick="focusEvidence()">聚焦证据</button></div><h2>覆盖达标后，为什么移动中仍会中断？</h2>${flow()}</div><div class="card pad"><div class="section-title"><span>当前要看的三项移动性证据</span></div>${evidence()}</div><div class="card answer"><div class="status-card"><div class="status-icon">✎</div><div><h3>我的作答</h3><p>完成右侧三步后提交，参与课堂讲评。</p></div></div><div class="steps"><div class="step ${state.submitted?'':'active'}"><b>待提交</b><br><span>尚未提交本页作答</span></div><div class="step ${state.submitted?'active':''}"><b>已提交</b><br><span>等待教师讲评</span></div><div class="step"><b>讲评中</b><br><span>教师正在讲解本页</span></div></div><button class="primary" onclick="submitAnswer()">提交作答</button></div></section>`}
function renderMain(){const map={course,project,task,self,graph,teacher,projector,follow};$('#main').innerHTML=map[state.view]();}
function renderSide(){if(state.view==='follow'){$('#side').innerHTML=sideStudent();bindInputs();}else{$('#side').innerHTML=sideDefault();}}
function bindInputs(){['why','conclusion'].forEach(id=>{const el=$('#'+id);if(el)el.oninput=e=>{state.answer[id]=e.target.value;$('#'+id+'Count').textContent=e.target.value.length}});['q1','q2'].forEach(id=>{const el=$('#'+id);if(el)el.onchange=e=>state.answer[id]=e.target.value});}
function render(){document.body.classList.toggle('teacher-mode',['teacher','projector'].includes(state.view));document.body.classList.toggle('graph-mode',state.view==='graph');renderTabs();renderLeft();renderMain();renderSide();$('#modeText').textContent=(activeTab()==='教师'?'教师端':'学生端')+' · '+(state.free?'自学自由':'课堂跟随');$('#toggleMode').textContent=state.free?'恢复课堂跟随':'转入自学自由';}
function go(id){state.view=id;render();toast('已切换：'+views.find(v=>v.id===id).title)}
function fillDemo(){state.answer={q1:'移动路径',q2:'切换成功率未达标',why:'切换成功率低于目标，且重建次数偏多。',conclusion:'覆盖改善，但移动性未闭环，需要继续复核切换参数。'};render();toast('已填入示例作答')}
function submitAnswer(){if(!state.answer.q1||!state.answer.q2||!state.answer.conclusion.trim()){toast('请先完成三项课堂小任务');return}state.submitted=true;render();toast('作答已提交，等待教师讲评')}
function focusEvidence(){document.querySelectorAll('.ev').forEach((e,i)=>setTimeout(()=>{e.classList.add('active-focus');setTimeout(()=>e.classList.remove('active-focus'),900)},i*180));}
$('#toggleMode').onclick=()=>{state.free=!state.free;render();toast(state.free?'已转入自学自由':'已恢复课堂跟随')};$('#openProjector').onclick=()=>go('projector');$('#syncBtn').onclick=()=>{state.free=false;state.view='follow';render();toast('已同步学生端到课堂跟随页')};$('#pushBtn').onclick=()=>{state.pushed=true;state.view='follow';render();toast('课堂练习已推送到学生端')};$('#teachBtn').onclick=()=>{state.playing=!state.playing;toast(state.playing?'开始讲解：聚焦移动性证据':'已暂停讲解');if(state.view!=='follow')go('follow');setTimeout(focusEvidence,120)};
render();
